/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Login_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Login_GUI
     */
    public Login_GUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOGIN_LABEL = new javax.swing.JLabel();
        LOGIN_TXT = new javax.swing.JTextField();
        SENHA_LABEL = new javax.swing.JLabel();
        ACESSAR_BTN = new javax.swing.JButton();
        SENHA_TXT = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        LOGIN_LABEL.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        LOGIN_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGIN_LABEL.setText("LOGIN");
        jPanel1.add(LOGIN_LABEL);
        LOGIN_LABEL.setBounds(180, 120, 280, 38);
        jPanel1.add(LOGIN_TXT);
        LOGIN_TXT.setBounds(180, 160, 280, 30);

        SENHA_LABEL.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        SENHA_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SENHA_LABEL.setText("SENHA");
        jPanel1.add(SENHA_LABEL);
        SENHA_LABEL.setBounds(180, 210, 280, 38);

        ACESSAR_BTN.setText("ACESSAR");
        ACESSAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACESSAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ACESSAR_BTN);
        ACESSAR_BTN.setBounds(500, 380, 100, 30);

        SENHA_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENHA_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(SENHA_TXT);
        SENHA_TXT.setBounds(180, 250, 280, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("X");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 10, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(640, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ACESSAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACESSAR_BTNActionPerformed
        Controller.Verifica_DAO.verifica();
    }//GEN-LAST:event_ACESSAR_BTNActionPerformed

    private void SENHA_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENHA_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SENHA_TXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACESSAR_BTN;
    private javax.swing.JLabel LOGIN_LABEL;
    public static javax.swing.JTextField LOGIN_TXT;
    private javax.swing.JLabel SENHA_LABEL;
    public static javax.swing.JPasswordField SENHA_TXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
