/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HEIGHT_TXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        WIDTH_TXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MQUAD_TXT = new javax.swing.JLabel();
        PCT_TXT = new javax.swing.JLabel();
        CALC_BTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        NBLOCKS_TXT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cálculo de Quantidade de Blocos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 30, 750, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel2.setText("Largura da Parede");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 220, 190, 30);

        HEIGHT_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel1.add(HEIGHT_TXT);
        HEIGHT_TXT.setBounds(50, 170, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel4.setText("(m)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 170, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel5.setText("(m)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 250, 40, 30);

        WIDTH_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel1.add(WIDTH_TXT);
        WIDTH_TXT.setBounds(50, 250, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel6.setText("Altura da Parede");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 140, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel7.setText("1 Bloco = 0,18m X 0,38m");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 150, 260, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel8.setText("serão necessários");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 250, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel10.setText("A perda de material é de:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 320, 250, 30);

        MQUAD_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        MQUAD_TXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(MQUAD_TXT);
        MQUAD_TXT.setBounds(560, 220, 180, 30);

        PCT_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        PCT_TXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(PCT_TXT);
        PCT_TXT.setBounds(610, 320, 130, 30);

        CALC_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        CALC_BTN.setText("CALCULAR");
        CALC_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALC_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CALC_BTN);
        CALC_BTN.setBounds(50, 300, 190, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel11.setText("Para uma parede de");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 220, 200, 30);

        NBLOCKS_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        NBLOCKS_TXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(NBLOCKS_TXT);
        NBLOCKS_TXT.setBounds(530, 250, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(750, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CALC_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALC_BTNActionPerformed
        Controller.Calculos_DAO.calcParede();
    }//GEN-LAST:event_CALC_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALC_BTN;
    public static javax.swing.JTextField HEIGHT_TXT;
    public static javax.swing.JLabel MQUAD_TXT;
    public static javax.swing.JLabel NBLOCKS_TXT;
    public static javax.swing.JLabel PCT_TXT;
    public static javax.swing.JTextField WIDTH_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
