/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.sun.scenario.effect.Blend;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        RESULT_TXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        VALUE1_TXT = new javax.swing.JTextField();
        TIMES_BTN = new javax.swing.JButton();
        MINUS_BTN = new javax.swing.JButton();
        SUM_BTN = new javax.swing.JButton();
        EXIT_BTN = new javax.swing.JButton();
        txtRESULT_TXT = new javax.swing.JLabel();
        RESULT_TXT = new javax.swing.JTextField();
        DIV_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CLEAR_BTN = new javax.swing.JToggleButton();
        VALUE2_TXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RESULT2_TXT = new javax.swing.JLabel();
        PCT_BTN = new javax.swing.JButton();
        POW_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel.setBackground(new java.awt.Color(0, 0, 0));
        jPanel.setLayout(null);

        VALUE1_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel.add(VALUE1_TXT);
        VALUE1_TXT.setBounds(140, 160, 140, 30);

        TIMES_BTN.setBackground(new java.awt.Color(0, 204, 204));
        TIMES_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        TIMES_BTN.setText("X");
        TIMES_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIMES_BTNActionPerformed(evt);
            }
        });
        jPanel.add(TIMES_BTN);
        TIMES_BTN.setBounds(240, 430, 50, 50);

        MINUS_BTN.setBackground(new java.awt.Color(0, 204, 204));
        MINUS_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        MINUS_BTN.setText("-");
        MINUS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINUS_BTNActionPerformed(evt);
            }
        });
        jPanel.add(MINUS_BTN);
        MINUS_BTN.setBounds(140, 430, 50, 50);

        SUM_BTN.setBackground(new java.awt.Color(0, 204, 204));
        SUM_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        SUM_BTN.setText("+");
        SUM_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUM_BTNActionPerformed(evt);
            }
        });
        jPanel.add(SUM_BTN);
        SUM_BTN.setBounds(40, 430, 50, 50);

        EXIT_BTN.setBackground(new java.awt.Color(0, 204, 204));
        EXIT_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        EXIT_BTN.setText("X");
        EXIT_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT_BTNActionPerformed(evt);
            }
        });
        jPanel.add(EXIT_BTN);
        EXIT_BTN.setBounds(530, 20, 50, 50);

        txtRESULT_TXT.setBackground(new java.awt.Color(255, 255, 255));
        txtRESULT_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        txtRESULT_TXT.setForeground(new java.awt.Color(255, 255, 255));
        txtRESULT_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRESULT_TXT.setText("RESULT");
        jPanel.add(txtRESULT_TXT);
        txtRESULT_TXT.setBounds(230, 220, 140, 30);

        RESULT_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        RESULT_TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RESULT_TXT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RESULT_TXT.setFocusable(false);
        jPanel.add(RESULT_TXT);
        RESULT_TXT.setBounds(230, 250, 140, 30);

        DIV_BTN.setBackground(new java.awt.Color(0, 204, 204));
        DIV_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        DIV_BTN.setText("/");
        DIV_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIV_BTNActionPerformed(evt);
            }
        });
        jPanel.add(DIV_BTN);
        DIV_BTN.setBounds(320, 430, 50, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VALUE 1");
        jPanel.add(jLabel1);
        jLabel1.setBounds(140, 130, 140, 30);

        jLabel5.setText("jLabel5");
        jPanel.add(jLabel5);
        jLabel5.setBounds(30, 20, 34, 14);

        CLEAR_BTN.setBackground(new java.awt.Color(0, 204, 204));
        CLEAR_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        CLEAR_BTN.setText("CLEAR");
        CLEAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_BTNActionPerformed(evt);
            }
        });
        jPanel.add(CLEAR_BTN);
        CLEAR_BTN.setBounds(210, 350, 180, 50);

        VALUE2_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jPanel.add(VALUE2_TXT);
        VALUE2_TXT.setBounds(330, 160, 140, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VALUE 2");
        jPanel.add(jLabel7);
        jLabel7.setBounds(330, 130, 140, 30);

        RESULT2_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        RESULT2_TXT.setForeground(new java.awt.Color(255, 255, 255));
        RESULT2_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel.add(RESULT2_TXT);
        RESULT2_TXT.setBounds(230, 290, 140, 30);

        PCT_BTN.setBackground(new java.awt.Color(0, 204, 204));
        PCT_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        PCT_BTN.setText("%");
        PCT_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCT_BTNActionPerformed(evt);
            }
        });
        jPanel.add(PCT_BTN);
        PCT_BTN.setBounds(400, 430, 60, 50);

        POW_BTN.setBackground(new java.awt.Color(0, 204, 204));
        POW_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        POW_BTN.setText("^");
        POW_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POW_BTNActionPerformed(evt);
            }
        });
        jPanel.add(POW_BTN);
        POW_BTN.setBounds(490, 430, 60, 50);

        getContentPane().add(jPanel);
        jPanel.setBounds(0, 0, 600, 500);

        setSize(new java.awt.Dimension(600, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DIV_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIV_BTNActionPerformed
        Model.Funcoes_DAO.div();
    }//GEN-LAST:event_DIV_BTNActionPerformed

    private void EXIT_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXIT_BTNActionPerformed

    private void SUM_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUM_BTNActionPerformed
        Model.Funcoes_DAO.sum();
    }//GEN-LAST:event_SUM_BTNActionPerformed

    private void MINUS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINUS_BTNActionPerformed
        Model.Funcoes_DAO.sub();
    }//GEN-LAST:event_MINUS_BTNActionPerformed

    private void TIMES_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIMES_BTNActionPerformed
        Model.Funcoes_DAO.mult();
    }//GEN-LAST:event_TIMES_BTNActionPerformed

    private void CLEAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_BTNActionPerformed
        Model.Funcoes_DAO.clear();
    }//GEN-LAST:event_CLEAR_BTNActionPerformed

    private void PCT_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCT_BTNActionPerformed
        Model.Funcoes_DAO.pct();
    }//GEN-LAST:event_PCT_BTNActionPerformed

    private void POW_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POW_BTNActionPerformed
        Model.Funcoes_DAO.pow();
    }//GEN-LAST:event_POW_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CLEAR_BTN;
    private javax.swing.JButton DIV_BTN;
    private javax.swing.JButton EXIT_BTN;
    private javax.swing.JButton MINUS_BTN;
    private javax.swing.JButton PCT_BTN;
    private javax.swing.JButton POW_BTN;
    public static javax.swing.JLabel RESULT2_TXT;
    public static javax.swing.JTextField RESULT_TXT;
    private javax.swing.JButton SUM_BTN;
    private javax.swing.JButton TIMES_BTN;
    public static javax.swing.JTextField VALUE1_TXT;
    public static javax.swing.JTextField VALUE2_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel txtRESULT_TXT;
    // End of variables declaration//GEN-END:variables
}
