/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        Imagem1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NOME_TXT = new javax.swing.JTextField();
        SAIR_BTN = new javax.swing.JButton();
        MENSAGEM_BTN = new javax.swing.JButton();
        Imagem1 = new org.edisoncor.gui.panel.PanelImage();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jSpinField1 = new com.toedter.components.JSpinField();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("NOME:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 80, 30);

        NOME_TXT.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        NOME_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOME_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(NOME_TXT);
        NOME_TXT.setBounds(110, 20, 430, 30);

        SAIR_BTN.setText("Sair");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(540, 430, 100, 30);

        MENSAGEM_BTN.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        MENSAGEM_BTN.setText("Mensagem");
        MENSAGEM_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENSAGEM_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(MENSAGEM_BTN);
        MENSAGEM_BTN.setBounds(40, 60, 220, 35);

        Imagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/windowsxp.jpeg"))); // NOI18N
        Imagem1.setLayout(null);
        jPanel1.add(Imagem1);
        Imagem1.setBounds(20, 290, 320, 180);
        jPanel1.add(jCalendar1);
        jCalendar1.setBounds(280, 110, 250, 153);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(540, 120, 87, 20);
        jPanel1.add(jDayChooser1);
        jDayChooser1.setBounds(20, 110, 250, 150);
        jPanel1.add(jLocaleChooser1);
        jLocaleChooser1.setBounds(280, 80, 280, 20);
        jPanel1.add(jMonthChooser1);
        jMonthChooser1.setBounds(540, 160, 95, 20);
        jPanel1.add(jSpinField1);
        jSpinField1.setBounds(540, 200, 50, 20);
        jPanel1.add(jYearChooser1);
        jYearChooser1.setBounds(540, 240, 47, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(700, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NOME_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOME_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOME_TXTActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        Model.Mensagem_DAO.sair();
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void MENSAGEM_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENSAGEM_BTNActionPerformed
        Model.Mensagem_DAO.call();
    }//GEN-LAST:event_MENSAGEM_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.edisoncor.gui.panel.PanelImage Imagem1;
    private javax.swing.JButton MENSAGEM_BTN;
    public static javax.swing.JTextField NOME_TXT;
    private javax.swing.JButton SAIR_BTN;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables
}
