/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        SINGIN_BTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CLEAR_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Cliente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 40);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Est. Civil:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 50, 70, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(440, 120, 200, 20);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 100, 130, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(440, 70, 100, 20);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 50, 40, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(550, 70, 90, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(140, 70, 290, 20);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome Completo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 50, 130, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(300, 170, 130, 20);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nacionalidade:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 150, 100, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(140, 120, 290, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(140, 170, 150, 20);

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RG:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 100, 130, 20);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("data de nascimento:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 150, 130, 20);

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("UF:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(590, 150, 30, 20);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(440, 170, 140, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "MA", "AL" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(590, 170, 50, 20);

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Naturalidade:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(440, 150, 100, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(10, 220, 270, 20);

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Endereço:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 200, 130, 20);

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Número:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 200, 70, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(290, 220, 140, 20);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(440, 220, 200, 20);

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Complemento:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(440, 200, 110, 20);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(440, 270, 140, 20);

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CEP:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(440, 250, 110, 20);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(290, 270, 140, 20);

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bairro:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(290, 250, 70, 20);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(10, 270, 270, 20);

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Celular");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(150, 300, 130, 20);

        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(590, 270, 50, 20);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(10, 320, 130, 20);

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Email:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(290, 300, 70, 20);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(440, 320, 200, 20);

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cadastrado em:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(440, 300, 110, 20);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(290, 320, 140, 20);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(150, 320, 130, 20);

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Município:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 250, 130, 20);

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Telefone:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 300, 130, 20);

        SINGIN_BTN.setBackground(new java.awt.Color(255, 153, 51));
        SINGIN_BTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SINGIN_BTN.setForeground(new java.awt.Color(255, 255, 255));
        SINGIN_BTN.setText("Cadastrar");
        SINGIN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SINGIN_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SINGIN_BTN);
        SINGIN_BTN.setBounds(440, 350, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(14, 60, 120, 130);

        CLEAR_BTN.setBackground(new java.awt.Color(102, 204, 255));
        CLEAR_BTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CLEAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        CLEAR_BTN.setText("Limpar");
        CLEAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CLEAR_BTN);
        CLEAR_BTN.setBounds(550, 350, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(666, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void SINGIN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SINGIN_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SINGIN_BTNActionPerformed

    private void CLEAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEAR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR_BTN;
    private javax.swing.JButton SINGIN_BTN;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
