/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        PessoaALT_TXT.setVisible(false);
        PessoaPESO_TXT.setVisible(false);
        PessoaIDADE_TXT.setVisible(false);
        PessoaIMC_TXT.setVisible(false);
        PessoaNOME_TXT.setVisible(false);
        PessoaCLASS_TXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Calcular_IMC = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        Nome = new javax.swing.JLabel();
        Idade = new javax.swing.JLabel();
        Peso = new javax.swing.JLabel();
        Altura = new javax.swing.JLabel();
        NOME_TXT = new javax.swing.JTextField();
        IDADE_TXT = new javax.swing.JTextField();
        PESO_TXT = new javax.swing.JTextField();
        ALTURA_TXT = new javax.swing.JTextField();
        CALCULAR_BTN = new javax.swing.JButton();
        LIMPAR_BTN = new javax.swing.JButton();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        fitaMetrica = new org.edisoncor.gui.scrollBar.ScrollBarCustom();
        PessoaNOME_TXT = new javax.swing.JLabel();
        PessoaPESO_TXT = new javax.swing.JLabel();
        pessoaPeso = new javax.swing.JLabel();
        PessoaALT_TXT = new javax.swing.JLabel();
        pssoaAltura = new javax.swing.JLabel();
        pessoaIdade = new javax.swing.JLabel();
        PessoaIDADE_TXT = new javax.swing.JLabel();
        PessoaIMC_TXT = new javax.swing.JLabel();
        pessoaIMC = new javax.swing.JLabel();
        PessoaCLASS_TXT = new javax.swing.JLabel();
        pessoaClass = new javax.swing.JLabel();
        SAIR_BTN = new org.edisoncor.gui.button.ButtonAeroRound();
        ADM_BTN = new javax.swing.JRadioButton();
        QUIMICA_BTN = new javax.swing.JRadioButton();
        ADS_BTN = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        Calcular_IMC.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Calcular_IMC.setText("Calcular IMC");
        jPanel1.add(Calcular_IMC);
        Calcular_IMC.setBounds(280, 0, 170, 70);

        panelImage1.setEnabled(false);
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Classificação+do+IMC+para+adultos.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(50, 60, 350, 190);

        Nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nome.setText("Nome: ");
        jPanel1.add(Nome);
        Nome.setBounds(120, 290, 60, 30);

        Idade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Idade.setText("Idade:");
        jPanel1.add(Idade);
        Idade.setBounds(120, 330, 60, 30);

        Peso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Peso.setText("Peso:");
        jPanel1.add(Peso);
        Peso.setBounds(120, 370, 60, 30);

        Altura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Altura.setText("Altura:");
        jPanel1.add(Altura);
        Altura.setBounds(120, 410, 60, 30);

        NOME_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOME_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(NOME_TXT);
        NOME_TXT.setBounds(180, 290, 100, 30);

        IDADE_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDADE_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(IDADE_TXT);
        IDADE_TXT.setBounds(180, 330, 100, 30);

        PESO_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESO_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(PESO_TXT);
        PESO_TXT.setBounds(180, 370, 100, 30);

        ALTURA_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTURA_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(ALTURA_TXT);
        ALTURA_TXT.setBounds(180, 410, 100, 30);

        CALCULAR_BTN.setText("Calcular");
        CALCULAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULAR_BTN);
        CALCULAR_BTN.setBounds(130, 490, 90, 40);

        LIMPAR_BTN.setText("Limpar");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(240, 490, 90, 40);

        panelImage2.setEnabled(false);
        panelImage2.setFocusable(false);
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/stantingman.png"))); // NOI18N
        panelImage2.setOpaque(false);
        panelImage2.setRequestFocusEnabled(false);
        panelImage2.setLayout(null);

        fitaMetrica.setVisibleAmount(0);
        fitaMetrica.setEnabled(false);
        panelImage2.add(fitaMetrica);
        fitaMetrica.setBounds(150, 100, 17, 350);

        PessoaNOME_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PessoaNOME_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelImage2.add(PessoaNOME_TXT);
        PessoaNOME_TXT.setBounds(140, 60, 200, 40);

        PessoaPESO_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PessoaPESO_TXT.setForeground(new java.awt.Color(255, 255, 255));
        PessoaPESO_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelImage2.add(PessoaPESO_TXT);
        PessoaPESO_TXT.setBounds(210, 200, 60, 30);

        pessoaPeso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pessoaPeso.setForeground(new java.awt.Color(255, 255, 255));
        pessoaPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pessoaPeso.setText("Peso:");
        panelImage2.add(pessoaPeso);
        pessoaPeso.setBounds(210, 170, 60, 30);

        PessoaALT_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelImage2.add(PessoaALT_TXT);
        PessoaALT_TXT.setBounds(80, 280, 70, 30);

        pssoaAltura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pssoaAltura.setText("Altura:");
        panelImage2.add(pssoaAltura);
        pssoaAltura.setBounds(80, 250, 60, 30);

        pessoaIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pessoaIdade.setText("Idade:");
        panelImage2.add(pessoaIdade);
        pessoaIdade.setBounds(270, 90, 60, 30);

        PessoaIDADE_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelImage2.add(PessoaIDADE_TXT);
        PessoaIDADE_TXT.setBounds(330, 90, 70, 30);

        PessoaIMC_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelImage2.add(PessoaIMC_TXT);
        PessoaIMC_TXT.setBounds(320, 120, 90, 30);

        pessoaIMC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pessoaIMC.setText("IMC:");
        panelImage2.add(pessoaIMC);
        pessoaIMC.setBounds(270, 120, 60, 30);

        PessoaCLASS_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PessoaCLASS_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelImage2.add(PessoaCLASS_TXT);
        PessoaCLASS_TXT.setBounds(90, 470, 300, 40);

        pessoaClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pessoaClass.setText("Classificação:");
        panelImage2.add(pessoaClass);
        pessoaClass.setBounds(190, 440, 110, 40);

        jPanel1.add(panelImage2);
        panelImage2.setBounds(280, 10, 480, 520);

        SAIR_BTN.setBackground(new java.awt.Color(255, 0, 0));
        SAIR_BTN.setText("X");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(930, 10, 40, 40);

        buttonGroup1.add(ADM_BTN);
        ADM_BTN.setText("Admnistração");
        jPanel1.add(ADM_BTN);
        ADM_BTN.setBounds(750, 100, 120, 23);

        buttonGroup1.add(QUIMICA_BTN);
        QUIMICA_BTN.setText("Química");
        jPanel1.add(QUIMICA_BTN);
        QUIMICA_BTN.setBounds(750, 120, 120, 23);

        buttonGroup1.add(ADS_BTN);
        ADS_BTN.setText("ADS");
        jPanel1.add(ADS_BTN);
        ADS_BTN.setBounds(750, 140, 120, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rio de Janeiro", "São Paulo", "Paraná", "Roraima" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(760, 290, 130, 20);

        jCheckBox2.setText("jCheckBox2");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(780, 220, 100, 23);

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(780, 200, 100, 23);

        jCheckBox3.setText("jCheckBox3");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(780, 240, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(984, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NOME_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOME_TXTActionPerformed
       
    }//GEN-LAST:event_NOME_TXTActionPerformed

    private void IDADE_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDADE_TXTActionPerformed
        
    }//GEN-LAST:event_IDADE_TXTActionPerformed

    private void PESO_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESO_TXTActionPerformed
        
    }//GEN-LAST:event_PESO_TXTActionPerformed

    private void ALTURA_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTURA_TXTActionPerformed
        
    }//GEN-LAST:event_ALTURA_TXTActionPerformed

    private void CALCULAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_BTNActionPerformed
        Model.Funcoes_DAO.calcular();
        Model.Funcoes_DAO.showRes();
    }//GEN-LAST:event_CALCULAR_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        Model.Funcoes_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        Model.Funcoes_DAO.sair();
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ADM_BTN;
    private javax.swing.JRadioButton ADS_BTN;
    public static javax.swing.JTextField ALTURA_TXT;
    private javax.swing.JLabel Altura;
    private javax.swing.JButton CALCULAR_BTN;
    private javax.swing.JLabel Calcular_IMC;
    public static javax.swing.JTextField IDADE_TXT;
    private javax.swing.JLabel Idade;
    private javax.swing.JButton LIMPAR_BTN;
    public static javax.swing.JTextField NOME_TXT;
    private javax.swing.JLabel Nome;
    public static javax.swing.JTextField PESO_TXT;
    private javax.swing.JLabel Peso;
    public static javax.swing.JLabel PessoaALT_TXT;
    public static javax.swing.JLabel PessoaCLASS_TXT;
    public static javax.swing.JLabel PessoaIDADE_TXT;
    public static javax.swing.JLabel PessoaIMC_TXT;
    public static javax.swing.JLabel PessoaNOME_TXT;
    public static javax.swing.JLabel PessoaPESO_TXT;
    private javax.swing.JRadioButton QUIMICA_BTN;
    private org.edisoncor.gui.button.ButtonAeroRound SAIR_BTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.edisoncor.gui.scrollBar.ScrollBarCustom fitaMetrica;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JLabel pessoaClass;
    private javax.swing.JLabel pessoaIMC;
    private javax.swing.JLabel pessoaIdade;
    private javax.swing.JLabel pessoaPeso;
    private javax.swing.JLabel pssoaAltura;
    // End of variables declaration//GEN-END:variables
}
